// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_providers.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createAuthProvider = `-- name: CreateAuthProvider :one
INSERT INTO auth_providers (tenant_id, provider_type, config, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, provider_type, config, is_active, created_at, updated_at
`

type CreateAuthProviderParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	ProviderType string    `json:"provider_type"`
	Config       []byte    `json:"config"`
	IsActive     bool      `json:"is_active"`
}

func (q *Queries) CreateAuthProvider(ctx context.Context, arg CreateAuthProviderParams) (AuthProvider, error) {
	row := q.db.QueryRow(ctx, createAuthProvider,
		arg.TenantID,
		arg.ProviderType,
		arg.Config,
		arg.IsActive,
	)
	var i AuthProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderType,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAuthProvider = `-- name: DeleteAuthProvider :exec
DELETE FROM auth_providers WHERE id = $1
`

func (q *Queries) DeleteAuthProvider(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAuthProvider, id)
	return err
}

const getAuthProvider = `-- name: GetAuthProvider :one
SELECT id, tenant_id, provider_type, config, is_active, created_at, updated_at FROM auth_providers WHERE id = $1
`

func (q *Queries) GetAuthProvider(ctx context.Context, id int64) (AuthProvider, error) {
	row := q.db.QueryRow(ctx, getAuthProvider, id)
	var i AuthProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderType,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthProviderByTenantAndType = `-- name: GetAuthProviderByTenantAndType :one
SELECT id, tenant_id, provider_type, config, is_active, created_at, updated_at FROM auth_providers 
WHERE tenant_id = $1 AND provider_type = $2 AND is_active = true
`

type GetAuthProviderByTenantAndTypeParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	ProviderType string    `json:"provider_type"`
}

func (q *Queries) GetAuthProviderByTenantAndType(ctx context.Context, arg GetAuthProviderByTenantAndTypeParams) (AuthProvider, error) {
	row := q.db.QueryRow(ctx, getAuthProviderByTenantAndType, arg.TenantID, arg.ProviderType)
	var i AuthProvider
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderType,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAuthProvidersByTenant = `-- name: ListActiveAuthProvidersByTenant :many
SELECT id, tenant_id, provider_type, config, is_active, created_at, updated_at FROM auth_providers 
WHERE tenant_id = $1 AND is_active = true 
ORDER BY provider_type
`

func (q *Queries) ListActiveAuthProvidersByTenant(ctx context.Context, tenantID uuid.UUID) ([]AuthProvider, error) {
	rows, err := q.db.Query(ctx, listActiveAuthProvidersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthProvider{}
	for rows.Next() {
		var i AuthProvider
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderType,
			&i.Config,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthProvider = `-- name: UpdateAuthProvider :exec
UPDATE auth_providers 
SET provider_type = $2, config = $3, is_active = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateAuthProviderParams struct {
	ID           int64  `json:"id"`
	ProviderType string `json:"provider_type"`
	Config       []byte `json:"config"`
	IsActive     bool   `json:"is_active"`
}

func (q *Queries) UpdateAuthProvider(ctx context.Context, arg UpdateAuthProviderParams) error {
	_, err := q.db.Exec(ctx, updateAuthProvider,
		arg.ID,
		arg.ProviderType,
		arg.Config,
		arg.IsActive,
	)
	return err
}
