// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: class_levels.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteClass = `-- name: DeleteClass :exec
DELETE FROM class_levels 
WHERE class_level_id = $1
`

func (q *Queries) DeleteClass(ctx context.Context, classLevelID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClass, classLevelID)
	return err
}

const getClassByID = `-- name: GetClassByID :one
SELECT 
    class_level_id,
    class_name,
    class_code,
    display_order,
    description,
    is_lower_primary,
    is_upper_primary,
    is_secondary,
    is_higher_secondary,
    created_at
FROM class_levels 
WHERE class_level_id = $1
LIMIT 1
`

func (q *Queries) GetClassByID(ctx context.Context, classLevelID uuid.UUID) (ClassLevel, error) {
	row := q.db.QueryRow(ctx, getClassByID, classLevelID)
	var i ClassLevel
	err := row.Scan(
		&i.ClassLevelID,
		&i.ClassName,
		&i.ClassCode,
		&i.DisplayOrder,
		&i.Description,
		&i.IsLowerPrimary,
		&i.IsUpperPrimary,
		&i.IsSecondary,
		&i.IsHigherSecondary,
		&i.CreatedAt,
	)
	return i, err
}

const replaceClass = `-- name: ReplaceClass :one
UPDATE class_levels
SET
    class_name = $2,
    class_code = $3,
    display_order = $4,
    description = $5,
    is_lower_primary = $6,
    is_upper_primary = $7,
    is_secondary = $8,
    is_higher_secondary = $9
WHERE class_level_id = $1
RETURNING class_level_id, class_name, class_code, display_order, description, is_lower_primary, is_upper_primary, is_secondary, is_higher_secondary, created_at
`

type ReplaceClassParams struct {
	ClassLevelID      uuid.UUID   `json:"class_level_id"`
	ClassName         string      `json:"class_name"`
	ClassCode         string      `json:"class_code"`
	DisplayOrder      int32       `json:"display_order"`
	Description       pgtype.Text `json:"description"`
	IsLowerPrimary    pgtype.Bool `json:"is_lower_primary"`
	IsUpperPrimary    pgtype.Bool `json:"is_upper_primary"`
	IsSecondary       pgtype.Bool `json:"is_secondary"`
	IsHigherSecondary pgtype.Bool `json:"is_higher_secondary"`
}

func (q *Queries) ReplaceClass(ctx context.Context, arg ReplaceClassParams) (ClassLevel, error) {
	row := q.db.QueryRow(ctx, replaceClass,
		arg.ClassLevelID,
		arg.ClassName,
		arg.ClassCode,
		arg.DisplayOrder,
		arg.Description,
		arg.IsLowerPrimary,
		arg.IsUpperPrimary,
		arg.IsSecondary,
		arg.IsHigherSecondary,
	)
	var i ClassLevel
	err := row.Scan(
		&i.ClassLevelID,
		&i.ClassName,
		&i.ClassCode,
		&i.DisplayOrder,
		&i.Description,
		&i.IsLowerPrimary,
		&i.IsUpperPrimary,
		&i.IsSecondary,
		&i.IsHigherSecondary,
		&i.CreatedAt,
	)
	return i, err
}

const upsertClass = `-- name: UpsertClass :one
INSERT INTO class_levels (
    class_level_id,
    class_name,
    class_code,
    display_order,
    description,
    is_lower_primary,
    is_upper_primary,
    is_secondary,
    is_higher_secondary
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (class_level_id) 
DO UPDATE SET
    class_name = EXCLUDED.class_name,
    class_code = EXCLUDED.class_code,
    display_order = EXCLUDED.display_order,
    description = EXCLUDED.description,
    is_lower_primary = EXCLUDED.is_lower_primary,
    is_upper_primary = EXCLUDED.is_upper_primary,
    is_secondary = EXCLUDED.is_secondary,
    is_higher_secondary = EXCLUDED.is_higher_secondary
    -- created_at remains unchanged (no updated_at column)
RETURNING class_level_id, class_name, class_code, display_order, description, is_lower_primary, is_upper_primary, is_secondary, is_higher_secondary, created_at
`

type UpsertClassParams struct {
	ClassLevelID      uuid.UUID   `json:"class_level_id"`
	ClassName         string      `json:"class_name"`
	ClassCode         string      `json:"class_code"`
	DisplayOrder      int32       `json:"display_order"`
	Description       pgtype.Text `json:"description"`
	IsLowerPrimary    pgtype.Bool `json:"is_lower_primary"`
	IsUpperPrimary    pgtype.Bool `json:"is_upper_primary"`
	IsSecondary       pgtype.Bool `json:"is_secondary"`
	IsHigherSecondary pgtype.Bool `json:"is_higher_secondary"`
}

func (q *Queries) UpsertClass(ctx context.Context, arg UpsertClassParams) (ClassLevel, error) {
	row := q.db.QueryRow(ctx, upsertClass,
		arg.ClassLevelID,
		arg.ClassName,
		arg.ClassCode,
		arg.DisplayOrder,
		arg.Description,
		arg.IsLowerPrimary,
		arg.IsUpperPrimary,
		arg.IsSecondary,
		arg.IsHigherSecondary,
	)
	var i ClassLevel
	err := row.Scan(
		&i.ClassLevelID,
		&i.ClassName,
		&i.ClassCode,
		&i.DisplayOrder,
		&i.Description,
		&i.IsLowerPrimary,
		&i.IsUpperPrimary,
		&i.IsSecondary,
		&i.IsHigherSecondary,
		&i.CreatedAt,
	)
	return i, err
}
