// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shashisharma307703/vedantam/db/types"
)

type AcademicYear struct {
	AcademicYearID uuid.UUID        `json:"academic_year_id"`
	OrgID          uuid.UUID        `json:"org_id"`
	Year           string           `json:"year"`
	StartDate      pgtype.Date      `json:"start_date"`
	EndDate        pgtype.Date      `json:"end_date"`
	IsActive       pgtype.Bool      `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type AccountHead struct {
	AccountHeadID int32            `json:"account_head_id"`
	OrgID         uuid.UUID        `json:"org_id"`
	HeadName      pgtype.Text      `json:"head_name"`
	HeadCode      pgtype.Text      `json:"head_code"`
	HeadType      pgtype.Text      `json:"head_type"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type AdmissionDocument struct {
	AdmissionDocID  uuid.UUID        `json:"admission_doc_id"`
	AdmissionFormID uuid.UUID        `json:"admission_form_id"`
	DocumentType    pgtype.Text      `json:"document_type"`
	FilePath        pgtype.Text      `json:"file_path"`
	UploadDate      pgtype.Timestamp `json:"upload_date"`
}

type AdmissionForm struct {
	AdmissionFormID     uuid.UUID        `json:"admission_form_id"`
	OrgID               uuid.UUID        `json:"org_id"`
	ApplicantName       string           `json:"applicant_name"`
	ApplicantEmail      pgtype.Text      `json:"applicant_email"`
	ApplicantPhone      pgtype.Text      `json:"applicant_phone"`
	DateOfBirth         pgtype.Date      `json:"date_of_birth"`
	Gender              pgtype.Text      `json:"gender"`
	Address             pgtype.Text      `json:"address"`
	City                pgtype.Text      `json:"city"`
	State               pgtype.Text      `json:"state"`
	PostalCode          pgtype.Text      `json:"postal_code"`
	AppliedClassLevelID uuid.UUID        `json:"applied_class_level_id"`
	AppliedStreamID     pgtype.UUID      `json:"applied_stream_id"`
	PreviousSchool      pgtype.Text      `json:"previous_school"`
	PreviousMarks       pgtype.Numeric   `json:"previous_marks"`
	ParentName          pgtype.Text      `json:"parent_name"`
	ParentEmail         pgtype.Text      `json:"parent_email"`
	ParentPhone         pgtype.Text      `json:"parent_phone"`
	FormStatus          pgtype.Text      `json:"form_status"`
	ApplicationDate     pgtype.Timestamp `json:"application_date"`
	SubmittedDate       pgtype.Timestamp `json:"submitted_date"`
	ApprovalDate        pgtype.Timestamp `json:"approval_date"`
	ApprovedBy          pgtype.UUID      `json:"approved_by"`
	Remarks             pgtype.Text      `json:"remarks"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
}

type Announcement struct {
	AnnouncementID   uuid.UUID        `json:"announcement_id"`
	OrgID            uuid.UUID        `json:"org_id"`
	Title            string           `json:"title"`
	Content          string           `json:"content"`
	AnnouncementType pgtype.Text      `json:"announcement_type"`
	TargetAudience   []byte           `json:"target_audience"`
	CreatedBy        uuid.UUID        `json:"created_by"`
	PublishDate      pgtype.Timestamp `json:"publish_date"`
	ExpiryDate       pgtype.Timestamp `json:"expiry_date"`
	IsPublished      pgtype.Bool      `json:"is_published"`
	IsPinned         pgtype.Bool      `json:"is_pinned"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type AnnouncementsRead struct {
	ReadID         uuid.UUID        `json:"read_id"`
	AnnouncementID uuid.UUID        `json:"announcement_id"`
	UserID         uuid.UUID        `json:"user_id"`
	ReadDate       pgtype.Timestamp `json:"read_date"`
}

type Asset struct {
	AssetID          uuid.UUID        `json:"asset_id"`
	OrgID            uuid.UUID        `json:"org_id"`
	AssetName        pgtype.Text      `json:"asset_name"`
	AssetCode        string           `json:"asset_code"`
	AssetCategory    pgtype.Text      `json:"asset_category"`
	AssetLocation    pgtype.Text      `json:"asset_location"`
	PurchaseDate     pgtype.Date      `json:"purchase_date"`
	PurchaseValue    pgtype.Numeric   `json:"purchase_value"`
	CurrentValue     pgtype.Numeric   `json:"current_value"`
	DepreciationRate pgtype.Numeric   `json:"depreciation_rate"`
	AssetStatus      pgtype.Text      `json:"asset_status"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type Assignment struct {
	AssignmentID   uuid.UUID        `json:"assignment_id"`
	StaffID        uuid.UUID        `json:"staff_id"`
	SubjectID      uuid.UUID        `json:"subject_id"`
	SectionID      uuid.UUID        `json:"section_id"`
	Title          string           `json:"title"`
	Description    pgtype.Text      `json:"description"`
	AssignmentDate pgtype.Date      `json:"assignment_date"`
	SubmissionDate pgtype.Date      `json:"submission_date"`
	TotalMarks     pgtype.Int4      `json:"total_marks"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type AssignmentSubmission struct {
	SubmissionID      uuid.UUID        `json:"submission_id"`
	AssignmentID      uuid.UUID        `json:"assignment_id"`
	StudentID         uuid.UUID        `json:"student_id"`
	SubmissionDate    pgtype.Timestamp `json:"submission_date"`
	SubmissionFileUrl pgtype.Text      `json:"submission_file_url"`
	MarksObtained     pgtype.Int4      `json:"marks_obtained"`
	Feedback          pgtype.Text      `json:"feedback"`
	SubmittedBy       pgtype.UUID      `json:"submitted_by"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type AuditLog struct {
	AuditID    uuid.UUID        `json:"audit_id"`
	UserID     uuid.UUID        `json:"user_id"`
	OrgID      pgtype.UUID      `json:"org_id"`
	Action     string           `json:"action"`
	Module     string           `json:"module"`
	EntityType pgtype.Text      `json:"entity_type"`
	EntityID   pgtype.Text      `json:"entity_id"`
	OldValues  []byte           `json:"old_values"`
	NewValues  []byte           `json:"new_values"`
	IpAddress  pgtype.Text      `json:"ip_address"`
	Timestamp  pgtype.Timestamp `json:"timestamp"`
}

type BiometricDevice struct {
	DeviceID           int32            `json:"device_id"`
	OrgID              uuid.UUID        `json:"org_id"`
	DeviceName         pgtype.Text      `json:"device_name"`
	DeviceSerialNumber string           `json:"device_serial_number"`
	DeviceType         pgtype.Text      `json:"device_type"`
	Location           pgtype.Text      `json:"location"`
	IpAddress          pgtype.Text      `json:"ip_address"`
	IsActive           pgtype.Bool      `json:"is_active"`
	LastSyncTime       pgtype.Timestamp `json:"last_sync_time"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type BiometricMapping struct {
	MappingID     int32            `json:"mapping_id"`
	UserID        uuid.UUID        `json:"user_id"`
	BiometricID   string           `json:"biometric_id"`
	BiometricType pgtype.Text      `json:"biometric_type"`
	DeviceID      int32            `json:"device_id"`
	MappedDate    pgtype.Timestamp `json:"mapped_date"`
	IsActive      pgtype.Bool      `json:"is_active"`
}

type BookIssueReturn struct {
	TransactionID      uuid.UUID        `json:"transaction_id"`
	CopyID             uuid.UUID        `json:"copy_id"`
	UserID             uuid.UUID        `json:"user_id"`
	OrgID              uuid.UUID        `json:"org_id"`
	IssueDate          pgtype.Date      `json:"issue_date"`
	ExpectedReturnDate pgtype.Date      `json:"expected_return_date"`
	ActualReturnDate   pgtype.Date      `json:"actual_return_date"`
	IsReturned         pgtype.Bool      `json:"is_returned"`
	IssuedBy           pgtype.UUID      `json:"issued_by"`
	ReturnedBy         pgtype.UUID      `json:"returned_by"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type ClassLevel struct {
	ClassLevelID      uuid.UUID        `json:"class_level_id"`
	ClassName         string           `json:"class_name"`
	ClassCode         string           `json:"class_code"`
	DisplayOrder      int32            `json:"display_order"`
	Description       pgtype.Text      `json:"description"`
	IsLowerPrimary    pgtype.Bool      `json:"is_lower_primary"`
	IsUpperPrimary    pgtype.Bool      `json:"is_upper_primary"`
	IsSecondary       pgtype.Bool      `json:"is_secondary"`
	IsHigherSecondary pgtype.Bool      `json:"is_higher_secondary"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type ClassSubject struct {
	ClassSubjectID uuid.UUID        `json:"class_subject_id"`
	OrgID          uuid.UUID        `json:"org_id"`
	ClassLevelID   uuid.UUID        `json:"class_level_id"`
	StreamID       pgtype.UUID      `json:"stream_id"`
	SubjectID      uuid.UUID        `json:"subject_id"`
	AcademicYearID uuid.UUID        `json:"academic_year_id"`
	IsActive       pgtype.Bool      `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Complaint struct {
	ComplaintID           uuid.UUID        `json:"complaint_id"`
	OrgID                 uuid.UUID        `json:"org_id"`
	ComplainantID         uuid.UUID        `json:"complainant_id"`
	ComplaintType         pgtype.Text      `json:"complaint_type"`
	ComplaintDescription  pgtype.Text      `json:"complaint_description"`
	ComplaintDate         pgtype.Timestamp `json:"complaint_date"`
	Priority              pgtype.Text      `json:"priority"`
	Status                pgtype.Text      `json:"status"`
	AssignedTo            pgtype.UUID      `json:"assigned_to"`
	ResolutionDescription pgtype.Text      `json:"resolution_description"`
	ResolvedDate          pgtype.Timestamp `json:"resolved_date"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
}

type Course struct {
	CourseID     uuid.UUID        `json:"course_id"`
	OrgID        uuid.UUID        `json:"org_id"`
	CourseName   string           `json:"course_name"`
	CourseCode   string           `json:"course_code"`
	Description  pgtype.Text      `json:"description"`
	InstructorID pgtype.UUID      `json:"instructor_id"`
	StartDate    pgtype.Date      `json:"start_date"`
	EndDate      pgtype.Date      `json:"end_date"`
	CourseStatus pgtype.Text      `json:"course_status"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type CourseAssessment struct {
	AssessmentID   uuid.UUID   `json:"assessment_id"`
	CourseID       uuid.UUID   `json:"course_id"`
	AssessmentName pgtype.Text `json:"assessment_name"`
	AssessmentType pgtype.Text `json:"assessment_type"`
	TotalMarks     pgtype.Int4 `json:"total_marks"`
	PassingMarks   pgtype.Int4 `json:"passing_marks"`
	DueDate        pgtype.Date `json:"due_date"`
}

type CourseAssessmentResult struct {
	ResultID       uuid.UUID        `json:"result_id"`
	AssessmentID   uuid.UUID        `json:"assessment_id"`
	UserID         uuid.UUID        `json:"user_id"`
	MarksObtained  pgtype.Int4      `json:"marks_obtained"`
	SubmissionDate pgtype.Timestamp `json:"submission_date"`
	Feedback       pgtype.Text      `json:"feedback"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type CourseEnrollment struct {
	EnrollmentID         uuid.UUID        `json:"enrollment_id"`
	CourseID             uuid.UUID        `json:"course_id"`
	UserID               uuid.UUID        `json:"user_id"`
	EnrollmentDate       pgtype.Timestamp `json:"enrollment_date"`
	CompletionPercentage pgtype.Int4      `json:"completion_percentage"`
	Status               pgtype.Text      `json:"status"`
}

type CourseModule struct {
	ModuleID       uuid.UUID        `json:"module_id"`
	CourseID       uuid.UUID        `json:"course_id"`
	ModuleName     pgtype.Text      `json:"module_name"`
	ModuleSequence pgtype.Int4      `json:"module_sequence"`
	ModuleContent  pgtype.Text      `json:"module_content"`
	ContentFileUrl pgtype.Text      `json:"content_file_url"`
	IsPublished    pgtype.Bool      `json:"is_published"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Driver struct {
	DriverID              uuid.UUID        `json:"driver_id"`
	OrgID                 uuid.UUID        `json:"org_id"`
	StaffID               pgtype.UUID      `json:"staff_id"`
	DriverName            string           `json:"driver_name"`
	LicenseNumber         string           `json:"license_number"`
	LicenseExpiry         pgtype.Date      `json:"license_expiry"`
	PhoneNumber           pgtype.Text      `json:"phone_number"`
	Address               pgtype.Text      `json:"address"`
	DateOfJoining         pgtype.Date      `json:"date_of_joining"`
	BackgroundCheckStatus pgtype.Text      `json:"background_check_status"`
	DriverStatus          pgtype.Text      `json:"driver_status"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
}

type EmailNotification struct {
	EmailID          uuid.UUID        `json:"email_id"`
	OrgID            pgtype.UUID      `json:"org_id"`
	RecipientEmail   pgtype.Text      `json:"recipient_email"`
	EmailSubject     pgtype.Text      `json:"email_subject"`
	EmailContent     pgtype.Text      `json:"email_content"`
	EmailTemplate    pgtype.Text      `json:"email_template"`
	NotificationType pgtype.Text      `json:"notification_type"`
	SentBy           pgtype.UUID      `json:"sent_by"`
	SentDate         pgtype.Timestamp `json:"sent_date"`
	DeliveryStatus   pgtype.Text      `json:"delivery_status"`
	DeliveryResponse pgtype.Text      `json:"delivery_response"`
}

type Exam struct {
	ExamID         uuid.UUID        `json:"exam_id"`
	ExamTypeID     int32            `json:"exam_type_id"`
	AcademicYearID uuid.UUID        `json:"academic_year_id"`
	ExamName       string           `json:"exam_name"`
	Description    pgtype.Text      `json:"description"`
	ExamStartDate  pgtype.Date      `json:"exam_start_date"`
	ExamEndDate    pgtype.Date      `json:"exam_end_date"`
	ExamStatus     pgtype.Text      `json:"exam_status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type ExamAnalytic struct {
	AnalyticsID       uuid.UUID        `json:"analytics_id"`
	ExamID            uuid.UUID        `json:"exam_id"`
	ClassLevelID      uuid.UUID        `json:"class_level_id"`
	SubjectID         uuid.UUID        `json:"subject_id"`
	TotalStudents     pgtype.Int4      `json:"total_students"`
	PresentStudents   pgtype.Int4      `json:"present_students"`
	AbsentStudents    pgtype.Int4      `json:"absent_students"`
	PassedStudents    pgtype.Int4      `json:"passed_students"`
	FailedStudents    pgtype.Int4      `json:"failed_students"`
	AverageMarks      pgtype.Numeric   `json:"average_marks"`
	HighestMarks      pgtype.Numeric   `json:"highest_marks"`
	LowestMarks       pgtype.Numeric   `json:"lowest_marks"`
	StandardDeviation pgtype.Numeric   `json:"standard_deviation"`
	AnalyticsDate     pgtype.Timestamp `json:"analytics_date"`
}

type ExamResult struct {
	ResultID      uuid.UUID        `json:"result_id"`
	StudentID     uuid.UUID        `json:"student_id"`
	ExamID        uuid.UUID        `json:"exam_id"`
	SectionID     uuid.UUID        `json:"section_id"`
	TotalMarks    pgtype.Numeric   `json:"total_marks"`
	ObtainedMarks pgtype.Numeric   `json:"obtained_marks"`
	Percentage    pgtype.Numeric   `json:"percentage"`
	GradeID       pgtype.Int4      `json:"grade_id"`
	Status        string           `json:"status"`
	ResultDate    pgtype.Timestamp `json:"result_date"`
	Published     pgtype.Bool      `json:"published"`
	PublishedDate pgtype.Timestamp `json:"published_date"`
}

type ExamSchedule struct {
	ScheduleID      uuid.UUID        `json:"schedule_id"`
	ExamID          uuid.UUID        `json:"exam_id"`
	SubjectID       uuid.UUID        `json:"subject_id"`
	ClassLevelID    uuid.UUID        `json:"class_level_id"`
	StreamID        pgtype.UUID      `json:"stream_id"`
	ExamDate        pgtype.Date      `json:"exam_date"`
	StartTime       pgtype.Time      `json:"start_time"`
	EndTime         pgtype.Time      `json:"end_time"`
	TotalMarks      pgtype.Int4      `json:"total_marks"`
	PassingMarks    pgtype.Int4      `json:"passing_marks"`
	DurationMinutes pgtype.Int4      `json:"duration_minutes"`
	Location        pgtype.Text      `json:"location"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type ExamType struct {
	ExamTypeID   int32            `json:"exam_type_id"`
	OrgID        uuid.UUID        `json:"org_id"`
	ExamTypeName string           `json:"exam_type_name"`
	ExamCode     string           `json:"exam_code"`
	Description  pgtype.Text      `json:"description"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type FeeAlert struct {
	AlertID        uuid.UUID        `json:"alert_id"`
	StudentID      uuid.UUID        `json:"student_id"`
	AcademicYearID uuid.UUID        `json:"academic_year_id"`
	DueAmount      pgtype.Numeric   `json:"due_amount"`
	DueDate        pgtype.Date      `json:"due_date"`
	AlertStatus    pgtype.Text      `json:"alert_status"`
	AlertCount     pgtype.Int4      `json:"alert_count"`
	LastAlertDate  pgtype.Timestamp `json:"last_alert_date"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type FeeConcession struct {
	ConcessionID         uuid.UUID        `json:"concession_id"`
	StudentID            uuid.UUID        `json:"student_id"`
	AcademicYearID       uuid.UUID        `json:"academic_year_id"`
	ConcessionType       pgtype.Text      `json:"concession_type"`
	ConcessionPercentage pgtype.Numeric   `json:"concession_percentage"`
	ConcessionAmount     pgtype.Numeric   `json:"concession_amount"`
	Reason               pgtype.Text      `json:"reason"`
	ApprovedBy           pgtype.UUID      `json:"approved_by"`
	ApprovalDate         pgtype.Timestamp `json:"approval_date"`
	IsActive             pgtype.Bool      `json:"is_active"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
}

type FeeStructure struct {
	FeeStructureID uuid.UUID        `json:"fee_structure_id"`
	OrgID          uuid.UUID        `json:"org_id"`
	AcademicYearID uuid.UUID        `json:"academic_year_id"`
	ClassLevelID   uuid.UUID        `json:"class_level_id"`
	StreamID       pgtype.UUID      `json:"stream_id"`
	FeeType        string           `json:"fee_type"`
	Amount         pgtype.Numeric   `json:"amount"`
	Description    pgtype.Text      `json:"description"`
	IsMandatory    pgtype.Bool      `json:"is_mandatory"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type FeeTransaction struct {
	TransactionID        uuid.UUID        `json:"transaction_id"`
	StudentID            uuid.UUID        `json:"student_id"`
	AcademicYearID       uuid.UUID        `json:"academic_year_id"`
	TransactionDate      pgtype.Date      `json:"transaction_date"`
	AmountDue            pgtype.Numeric   `json:"amount_due"`
	AmountPaid           pgtype.Numeric   `json:"amount_paid"`
	PaymentMethod        string           `json:"payment_method"`
	TransactionReference pgtype.Text      `json:"transaction_reference"`
	PaymentStatus        pgtype.Text      `json:"payment_status"`
	Notes                pgtype.Text      `json:"notes"`
	CollectedBy          pgtype.UUID      `json:"collected_by"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
}

type FinancialReport struct {
	ReportID       uuid.UUID        `json:"report_id"`
	OrgID          uuid.UUID        `json:"org_id"`
	AcademicYearID uuid.UUID        `json:"academic_year_id"`
	ReportType     pgtype.Text      `json:"report_type"`
	ReportName     pgtype.Text      `json:"report_name"`
	StartDate      pgtype.Date      `json:"start_date"`
	EndDate        pgtype.Date      `json:"end_date"`
	TotalRevenue   pgtype.Numeric   `json:"total_revenue"`
	TotalExpense   pgtype.Numeric   `json:"total_expense"`
	NetProfit      pgtype.Numeric   `json:"net_profit"`
	ReportData     []byte           `json:"report_data"`
	GeneratedBy    pgtype.UUID      `json:"generated_by"`
	GeneratedDate  pgtype.Timestamp `json:"generated_date"`
}

type Grade struct {
	GradeID       int32          `json:"grade_id"`
	GradeScaleID  int32          `json:"grade_scale_id"`
	GradeLetter   pgtype.Text    `json:"grade_letter"`
	MinPercentage pgtype.Numeric `json:"min_percentage"`
	MaxPercentage pgtype.Numeric `json:"max_percentage"`
	GradePoint    pgtype.Numeric `json:"grade_point"`
	Description   pgtype.Text    `json:"description"`
}

type GradeScale struct {
	GradeScaleID int32            `json:"grade_scale_id"`
	OrgID        int32            `json:"org_id"`
	ScaleName    pgtype.Text      `json:"scale_name"`
	Description  pgtype.Text      `json:"description"`
	IsActive     pgtype.Bool      `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type HostelAllocation struct {
	AllocationID     uuid.UUID        `json:"allocation_id"`
	StudentID        uuid.UUID        `json:"student_id"`
	RoomID           uuid.UUID        `json:"room_id"`
	AcademicYearID   uuid.UUID        `json:"academic_year_id"`
	AllocationDate   pgtype.Date      `json:"allocation_date"`
	CheckoutDate     pgtype.Date      `json:"checkout_date"`
	AllocationStatus pgtype.Text      `json:"allocation_status"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type HostelBlock struct {
	BlockID    uuid.UUID        `json:"block_id"`
	OrgID      uuid.UUID        `json:"org_id"`
	BlockName  string           `json:"block_name"`
	BlockType  pgtype.Text      `json:"block_type"`
	TotalRooms pgtype.Int4      `json:"total_rooms"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type HostelRoom struct {
	RoomID     uuid.UUID        `json:"room_id"`
	BlockID    uuid.UUID        `json:"block_id"`
	RoomNumber string           `json:"room_number"`
	RoomType   pgtype.Text      `json:"room_type"`
	Capacity   pgtype.Int4      `json:"capacity"`
	RoomStatus pgtype.Text      `json:"room_status"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type InventoryItem struct {
	ItemID           uuid.UUID        `json:"item_id"`
	OrgID            uuid.UUID        `json:"org_id"`
	ItemName         string           `json:"item_name"`
	ItemCode         string           `json:"item_code"`
	Category         pgtype.Text      `json:"category"`
	Quantity         pgtype.Int4      `json:"quantity"`
	ReorderLevel     pgtype.Int4      `json:"reorder_level"`
	UnitPrice        pgtype.Numeric   `json:"unit_price"`
	SupplierName     pgtype.Text      `json:"supplier_name"`
	LastPurchaseDate pgtype.Date      `json:"last_purchase_date"`
	ItemStatus       pgtype.Text      `json:"item_status"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type InventoryTransaction struct {
	TransactionID   uuid.UUID        `json:"transaction_id"`
	ItemID          uuid.UUID        `json:"item_id"`
	TransactionType string           `json:"transaction_type"`
	Quantity        pgtype.Int4      `json:"quantity"`
	TransactionDate pgtype.Date      `json:"transaction_date"`
	ReferenceID     pgtype.Text      `json:"reference_id"`
	Notes           pgtype.Text      `json:"notes"`
	CreatedBy       pgtype.UUID      `json:"created_by"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type Invoice struct {
	InvoiceID      uuid.UUID        `json:"invoice_id"`
	OrgID          uuid.UUID        `json:"org_id"`
	StudentID      uuid.UUID        `json:"student_id"`
	AcademicYearID uuid.UUID        `json:"academic_year_id"`
	InvoiceNumber  string           `json:"invoice_number"`
	InvoiceDate    pgtype.Date      `json:"invoice_date"`
	TotalAmount    pgtype.Numeric   `json:"total_amount"`
	TaxAmount      pgtype.Numeric   `json:"tax_amount"`
	DiscountAmount pgtype.Numeric   `json:"discount_amount"`
	NetAmount      pgtype.Numeric   `json:"net_amount"`
	DueDate        pgtype.Date      `json:"due_date"`
	PaymentStatus  pgtype.Text      `json:"payment_status"`
	InvoiceData    []byte           `json:"invoice_data"`
	GeneratedBy    pgtype.UUID      `json:"generated_by"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type LeaveApplication struct {
	LeaveApplicationID uuid.UUID        `json:"leave_application_id"`
	UserID             uuid.UUID        `json:"user_id"`
	OrgID              uuid.UUID        `json:"org_id"`
	LeaveTypeID        int32            `json:"leave_type_id"`
	StartDate          pgtype.Date      `json:"start_date"`
	EndDate            pgtype.Date      `json:"end_date"`
	NumberOfDays       pgtype.Int4      `json:"number_of_days"`
	Reason             pgtype.Text      `json:"reason"`
	ApplicationStatus  pgtype.Text      `json:"application_status"`
	ApprovedBy         pgtype.UUID      `json:"approved_by"`
	ApprovalDate       pgtype.Timestamp `json:"approval_date"`
	RejectionReason    pgtype.Text      `json:"rejection_reason"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type LeaveType struct {
	LeaveTypeID         int32            `json:"leave_type_id"`
	OrgID               uuid.UUID        `json:"org_id"`
	LeaveTypeName       string           `json:"leave_type_name"`
	Description         pgtype.Text      `json:"description"`
	AnnualLimit         pgtype.Int4      `json:"annual_limit"`
	CarryForwardAllowed pgtype.Bool      `json:"carry_forward_allowed"`
	RequiresApproval    pgtype.Bool      `json:"requires_approval"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
}

type LedgerEntry struct {
	LedgerEntryID   uuid.UUID        `json:"ledger_entry_id"`
	AccountHeadID   int32            `json:"account_head_id"`
	TransactionDate pgtype.Date      `json:"transaction_date"`
	DebitAmount     pgtype.Numeric   `json:"debit_amount"`
	CreditAmount    pgtype.Numeric   `json:"credit_amount"`
	ReferenceID     pgtype.Text      `json:"reference_id"`
	ReferenceType   pgtype.Text      `json:"reference_type"`
	Description     pgtype.Text      `json:"description"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type LessonPlan struct {
	LessonPlanID        uuid.UUID        `json:"lesson_plan_id"`
	StaffID             uuid.UUID        `json:"staff_id"`
	SubjectID           uuid.UUID        `json:"subject_id"`
	ClassLevelID        uuid.UUID        `json:"class_level_id"`
	StreamID            pgtype.UUID      `json:"stream_id"`
	AcademicYearID      uuid.UUID        `json:"academic_year_id"`
	LessonTitle         string           `json:"lesson_title"`
	LessonDate          pgtype.Date      `json:"lesson_date"`
	LessonContent       pgtype.Text      `json:"lesson_content"`
	LearningOutcomes    pgtype.Text      `json:"learning_outcomes"`
	TeachingMethodology pgtype.Text      `json:"teaching_methodology"`
	ResourcesRequired   pgtype.Text      `json:"resources_required"`
	AssessmentMethod    pgtype.Text      `json:"assessment_method"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
}

type LibraryBook struct {
	BookID          uuid.UUID      `json:"book_id"`
	OrgID           uuid.UUID      `json:"org_id"`
	Isbn            pgtype.Text    `json:"isbn"`
	Title           string         `json:"title"`
	Author          pgtype.Text    `json:"author"`
	Publisher       pgtype.Text    `json:"publisher"`
	PublicationYear pgtype.Int4    `json:"publication_year"`
	Edition         pgtype.Text    `json:"edition"`
	Category        pgtype.Text    `json:"category"`
	Subject         pgtype.Text    `json:"subject"`
	TotalCopies     pgtype.Int4    `json:"total_copies"`
	AvailableCopies pgtype.Int4    `json:"available_copies"`
	BookPrice       pgtype.Numeric `json:"book_price"`
	AddedDate       pgtype.Date    `json:"added_date"`
	BookStatus      pgtype.Text    `json:"book_status"`
}

type LibraryBookCopy struct {
	CopyID          uuid.UUID        `json:"copy_id"`
	OrgID           uuid.UUID        `json:"org_id"`
	BookID          uuid.UUID        `json:"book_id"`
	BarcodeNumber   string           `json:"barcode_number"`
	CopyNumber      pgtype.Int4      `json:"copy_number"`
	AcquisitionDate pgtype.Date      `json:"acquisition_date"`
	CopyStatus      pgtype.Text      `json:"copy_status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type LibraryFine struct {
	FineID        uuid.UUID      `json:"fine_id"`
	TransactionID uuid.UUID      `json:"transaction_id"`
	FineAmount    pgtype.Numeric `json:"fine_amount"`
	FineDate      pgtype.Date    `json:"fine_date"`
	IsPaid        pgtype.Bool    `json:"is_paid"`
	PaidDate      pgtype.Date    `json:"paid_date"`
}

type MarksEntry struct {
	MarksEntryID   uuid.UUID        `json:"marks_entry_id"`
	ExamScheduleID uuid.UUID        `json:"exam_schedule_id"`
	StudentID      uuid.UUID        `json:"student_id"`
	MarksObtained  pgtype.Numeric   `json:"marks_obtained"`
	EntryDate      pgtype.Timestamp `json:"entry_date"`
	EnteredBy      pgtype.UUID      `json:"entered_by"`
	IsAbsent       pgtype.Bool      `json:"is_absent"`
	Remarks        pgtype.Text      `json:"remarks"`
}

type Message struct {
	MessageID      uuid.UUID        `json:"message_id"`
	SenderID       uuid.UUID        `json:"sender_id"`
	RecipientID    uuid.UUID        `json:"recipient_id"`
	OrgID          uuid.UUID        `json:"org_id"`
	Subject        pgtype.Text      `json:"subject"`
	MessageContent string           `json:"message_content"`
	AttachmentUrl  pgtype.Text      `json:"attachment_url"`
	IsRead         pgtype.Bool      `json:"is_read"`
	ReadDate       pgtype.Timestamp `json:"read_date"`
	MessageType    pgtype.Text      `json:"message_type"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type OnlinePayment struct {
	PaymentID              uuid.UUID        `json:"payment_id"`
	TransactionID          uuid.UUID        `json:"transaction_id"`
	GatewayID              int32            `json:"gateway_id"`
	GatewayTransactionID   pgtype.Text      `json:"gateway_transaction_id"`
	PaymentGatewayResponse []byte           `json:"payment_gateway_response"`
	PaymentStatus          pgtype.Text      `json:"payment_status"`
	Amount                 pgtype.Numeric   `json:"amount"`
	PaymentDate            pgtype.Timestamp `json:"payment_date"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
}

type Organization struct {
	OrgID             uuid.UUID        `json:"org_id"`
	OrgName           string           `json:"org_name"`
	OrgCode           string           `json:"org_code"`
	PhoneNumber       pgtype.Text      `json:"phone_number"`
	Email             pgtype.Text      `json:"email"`
	Website           pgtype.Text      `json:"website"`
	LogoUrl           pgtype.Text      `json:"logo_url"`
	Address           pgtype.Text      `json:"address"`
	City              pgtype.Text      `json:"city"`
	State             pgtype.Text      `json:"state"`
	Country           pgtype.Text      `json:"country"`
	PostalCode        pgtype.Text      `json:"postal_code"`
	EstablishedDate   types.CustomDate `json:"established_date"`
	AffiliationNumber pgtype.Text      `json:"affiliation_number"`
	LicenseNumber     pgtype.Text      `json:"license_number"`
	LicenseExpiry     types.CustomDate `json:"license_expiry"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type ParentStudentMapping struct {
	MappingID      uuid.UUID        `json:"mapping_id"`
	ParentID       uuid.UUID        `json:"parent_id"`
	StudentID      uuid.UUID        `json:"student_id"`
	Relationship   pgtype.Text      `json:"relationship"`
	PrimaryContact pgtype.Bool      `json:"primary_contact"`
	OrgID          uuid.UUID        `json:"org_id"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type PaymentGateway struct {
	GatewayID   int32            `json:"gateway_id"`
	OrgID       uuid.UUID        `json:"org_id"`
	GatewayName pgtype.Text      `json:"gateway_name"`
	ApiKey      pgtype.Text      `json:"api_key"`
	ApiSecret   pgtype.Text      `json:"api_secret"`
	MerchantID  pgtype.Text      `json:"merchant_id"`
	IsActive    pgtype.Bool      `json:"is_active"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Payroll struct {
	PayrollID      uuid.UUID        `json:"payroll_id"`
	StaffID        uuid.UUID        `json:"staff_id"`
	OrgID          uuid.UUID        `json:"org_id"`
	AcademicYearID pgtype.UUID      `json:"academic_year_id"`
	MonthOfPayroll pgtype.Int4      `json:"month_of_payroll"`
	YearOfPayroll  pgtype.Int4      `json:"year_of_payroll"`
	BasicSalary    pgtype.Numeric   `json:"basic_salary"`
	Allowances     []byte           `json:"allowances"`
	Deductions     []byte           `json:"deductions"`
	GrossSalary    pgtype.Numeric   `json:"gross_salary"`
	NetSalary      pgtype.Numeric   `json:"net_salary"`
	PaymentDate    pgtype.Date      `json:"payment_date"`
	PaymentMethod  pgtype.Text      `json:"payment_method"`
	PaymentStatus  pgtype.Text      `json:"payment_status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Permission struct {
	PermissionID   int32            `json:"permission_id"`
	PermissionName string           `json:"permission_name"`
	Description    pgtype.Text      `json:"description"`
	Module         pgtype.Text      `json:"module"`
	Action         pgtype.Text      `json:"action"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type ReportCard struct {
	ReportCardID   uuid.UUID        `json:"report_card_id"`
	StudentID      uuid.UUID        `json:"student_id"`
	AcademicYearID uuid.UUID        `json:"academic_year_id"`
	ExamID         pgtype.UUID      `json:"exam_id"`
	SectionID      uuid.UUID        `json:"section_id"`
	GeneratedDate  pgtype.Timestamp `json:"generated_date"`
	GeneratedBy    pgtype.UUID      `json:"generated_by"`
	ReportCardData []byte           `json:"report_card_data"`
	IsPrinted      pgtype.Bool      `json:"is_printed"`
	PrintedDate    pgtype.Timestamp `json:"printed_date"`
	SignedBy       pgtype.UUID      `json:"signed_by"`
}

type Role struct {
	RoleID      int32            `json:"role_id"`
	RoleName    string           `json:"role_name"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type RolePermission struct {
	RoleID       int32     `json:"role_id"`
	PermissionID int32     `json:"permission_id"`
	OrgID        uuid.UUID `json:"org_id"`
}

type Section struct {
	SectionID      uuid.UUID        `json:"section_id"`
	OrgID          uuid.UUID        `json:"org_id"`
	ClassLevelID   uuid.UUID        `json:"class_level_id"`
	StreamID       pgtype.UUID      `json:"stream_id"`
	SectionName    string           `json:"section_name"`
	SectionCode    string           `json:"section_code"`
	ClassTeacherID pgtype.UUID      `json:"class_teacher_id"`
	Capacity       pgtype.Int4      `json:"capacity"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type SmsGateway struct {
	SmsGatewayID int32            `json:"sms_gateway_id"`
	OrgID        uuid.UUID        `json:"org_id"`
	GatewayName  pgtype.Text      `json:"gateway_name"`
	ApiKey       pgtype.Text      `json:"api_key"`
	ApiUrl       pgtype.Text      `json:"api_url"`
	SenderID     pgtype.Text      `json:"sender_id"`
	IsActive     pgtype.Bool      `json:"is_active"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type SmsNotification struct {
	SmsID            uuid.UUID        `json:"sms_id"`
	OrgID            pgtype.UUID      `json:"org_id"`
	RecipientPhone   pgtype.Text      `json:"recipient_phone"`
	MessageContent   pgtype.Text      `json:"message_content"`
	NotificationType pgtype.Text      `json:"notification_type"`
	SentBy           pgtype.UUID      `json:"sent_by"`
	SentDate         pgtype.Timestamp `json:"sent_date"`
	DeliveryStatus   pgtype.Text      `json:"delivery_status"`
	DeliveryResponse pgtype.Text      `json:"delivery_response"`
}

type Staff struct {
	StaffID           uuid.UUID        `json:"staff_id"`
	UserID            uuid.UUID        `json:"user_id"`
	OrgID             uuid.UUID        `json:"org_id"`
	EmployeeID        string           `json:"employee_id"`
	Designation       pgtype.Text      `json:"designation"`
	Department        pgtype.Text      `json:"department"`
	Qualification     pgtype.Text      `json:"qualification"`
	Specialization    pgtype.Text      `json:"specialization"`
	DateOfJoining     pgtype.Date      `json:"date_of_joining"`
	DateOfBirth       pgtype.Date      `json:"date_of_birth"`
	EmployeeStatus    pgtype.Text      `json:"employee_status"`
	BankAccountNumber pgtype.Text      `json:"bank_account_number"`
	BankName          pgtype.Text      `json:"bank_name"`
	IfscCode          pgtype.Text      `json:"ifsc_code"`
	PanNumber         pgtype.Text      `json:"pan_number"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type StaffAttendance struct {
	StaffAttendanceID uuid.UUID        `json:"staff_attendance_id"`
	StaffID           uuid.UUID        `json:"staff_id"`
	AttendanceDate    pgtype.Date      `json:"attendance_date"`
	CheckInTime       pgtype.Time      `json:"check_in_time"`
	CheckOutTime      pgtype.Time      `json:"check_out_time"`
	Status            string           `json:"status"`
	BiometricID       pgtype.Text      `json:"biometric_id"`
	MarkedBy          pgtype.UUID      `json:"marked_by"`
	Remarks           pgtype.Text      `json:"remarks"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type StaffPerformanceEvaluation struct {
	EvaluationID            uuid.UUID        `json:"evaluation_id"`
	StaffID                 uuid.UUID        `json:"staff_id"`
	OrgID                   uuid.UUID        `json:"org_id"`
	AcademicYearID          uuid.UUID        `json:"academic_year_id"`
	EvaluationPeriod        pgtype.Text      `json:"evaluation_period"`
	OverallRating           pgtype.Numeric   `json:"overall_rating"`
	AttendanceRating        pgtype.Numeric   `json:"attendance_rating"`
	TeachingQuality         pgtype.Numeric   `json:"teaching_quality"`
	StudentFeedback         pgtype.Numeric   `json:"student_feedback"`
	ProfessionalDevelopment pgtype.Numeric   `json:"professional_development"`
	Comments                pgtype.Text      `json:"comments"`
	EvaluatedBy             pgtype.UUID      `json:"evaluated_by"`
	EvaluationDate          pgtype.Timestamp `json:"evaluation_date"`
	CreatedAt               pgtype.Timestamp `json:"created_at"`
}

type StaffSubjectAssignment struct {
	AssignmentID   uuid.UUID        `json:"assignment_id"`
	StaffID        uuid.UUID        `json:"staff_id"`
	SubjectID      uuid.UUID        `json:"subject_id"`
	SectionID      uuid.UUID        `json:"section_id"`
	AcademicYearID uuid.UUID        `json:"academic_year_id"`
	AssignedDate   pgtype.Date      `json:"assigned_date"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Stream struct {
	StreamID    uuid.UUID        `json:"stream_id"`
	StreamName  string           `json:"stream_name"`
	StreamCode  string           `json:"stream_code"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Student struct {
	StudentID             uuid.UUID        `json:"student_id"`
	UserID                uuid.UUID        `json:"user_id"`
	OrgID                 uuid.UUID        `json:"org_id"`
	AdmissionNumber       string           `json:"admission_number"`
	AdmissionDate         pgtype.Date      `json:"admission_date"`
	AdmissionClassLevelID pgtype.UUID      `json:"admission_class_level_id"`
	AdmissionStreamID     pgtype.UUID      `json:"admission_stream_id"`
	RollNumber            pgtype.Text      `json:"roll_number"`
	MotherName            pgtype.Text      `json:"mother_name"`
	FatherName            pgtype.Text      `json:"father_name"`
	GuardianName          pgtype.Text      `json:"guardian_name"`
	GuardianPhone         pgtype.Text      `json:"guardian_phone"`
	GuardianEmail         pgtype.Text      `json:"guardian_email"`
	EmergencyContact1     pgtype.Text      `json:"emergency_contact_1"`
	EmergencyContact2     pgtype.Text      `json:"emergency_contact_2"`
	BloodGroup            pgtype.Text      `json:"blood_group"`
	AadharNumber          pgtype.Text      `json:"aadhar_number"`
	BirthPlace            pgtype.Text      `json:"birth_place"`
	Nationality           pgtype.Text      `json:"nationality"`
	Religion              pgtype.Text      `json:"religion"`
	Caste                 pgtype.Text      `json:"caste"`
	Status                pgtype.Text      `json:"status"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type StudentAttendance struct {
	AttendanceID   uuid.UUID        `json:"attendance_id"`
	StudentID      uuid.UUID        `json:"student_id"`
	SectionID      uuid.UUID        `json:"section_id"`
	AttendanceDate pgtype.Date      `json:"attendance_date"`
	Status         string           `json:"status"`
	MarkedBy       pgtype.UUID      `json:"marked_by"`
	MarkedTime     pgtype.Timestamp `json:"marked_time"`
	Remarks        pgtype.Text      `json:"remarks"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type StudentDocument struct {
	DocumentID       uuid.UUID        `json:"document_id"`
	StudentID        uuid.UUID        `json:"student_id"`
	DocumentType     pgtype.Text      `json:"document_type"`
	DocumentName     pgtype.Text      `json:"document_name"`
	FilePath         pgtype.Text      `json:"file_path"`
	UploadDate       pgtype.Timestamp `json:"upload_date"`
	ExpiryDate       pgtype.Date      `json:"expiry_date"`
	Verified         pgtype.Bool      `json:"verified"`
	VerifiedBy       pgtype.UUID      `json:"verified_by"`
	VerificationDate pgtype.Timestamp `json:"verification_date"`
}

type StudentEnrollment struct {
	EnrollmentID   uuid.UUID        `json:"enrollment_id"`
	StudentID      uuid.UUID        `json:"student_id"`
	SectionID      uuid.UUID        `json:"section_id"`
	AcademicYearID uuid.UUID        `json:"academic_year_id"`
	EnrollmentDate pgtype.Date      `json:"enrollment_date"`
	Status         pgtype.Text      `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type StudentHealthRecord struct {
	HealthRecordID    uuid.UUID        `json:"health_record_id"`
	StudentID         uuid.UUID        `json:"student_id"`
	BloodGroup        pgtype.Text      `json:"blood_group"`
	Height            pgtype.Numeric   `json:"height"`
	Weight            pgtype.Numeric   `json:"weight"`
	VisionLeft        pgtype.Text      `json:"vision_left"`
	VisionRight       pgtype.Text      `json:"vision_right"`
	HearingStatus     pgtype.Text      `json:"hearing_status"`
	Allergies         pgtype.Text      `json:"allergies"`
	MedicalConditions pgtype.Text      `json:"medical_conditions"`
	Vaccinations      []byte           `json:"vaccinations"`
	LastCheckupDate   pgtype.Date      `json:"last_checkup_date"`
	Notes             pgtype.Text      `json:"notes"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type StudentPerformanceSummary struct {
	SummaryID            uuid.UUID        `json:"summary_id"`
	StudentID            uuid.UUID        `json:"student_id"`
	AcademicYearID       uuid.UUID        `json:"academic_year_id"`
	OrgID                uuid.UUID        `json:"org_id"`
	TotalClasses         pgtype.Int4      `json:"total_classes"`
	TotalPresent         pgtype.Int4      `json:"total_present"`
	AttendancePercentage pgtype.Numeric   `json:"attendance_percentage"`
	AverageMarks         pgtype.Numeric   `json:"average_marks"`
	PerformanceStatus    pgtype.Text      `json:"performance_status"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

type StudentPromotion struct {
	PromotionID      uuid.UUID        `json:"promotion_id"`
	StudentID        uuid.UUID        `json:"student_id"`
	FromClassLevelID uuid.UUID        `json:"from_class_level_id"`
	ToClassLevelID   uuid.UUID        `json:"to_class_level_id"`
	FromSectionID    pgtype.UUID      `json:"from_section_id"`
	ToSectionID      pgtype.UUID      `json:"to_section_id"`
	FromStreamID     pgtype.UUID      `json:"from_stream_id"`
	ToStreamID       pgtype.UUID      `json:"to_stream_id"`
	AcademicYearID   uuid.UUID        `json:"academic_year_id"`
	PromotionDate    pgtype.Date      `json:"promotion_date"`
	PromotionStatus  string           `json:"promotion_status"`
	Remarks          pgtype.Text      `json:"remarks"`
	ApprovedBy       pgtype.UUID      `json:"approved_by"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type StudentRouteAllocation struct {
	AllocationID   uuid.UUID        `json:"allocation_id"`
	StudentID      uuid.UUID        `json:"student_id"`
	RouteID        uuid.UUID        `json:"route_id"`
	VehicleID      uuid.UUID        `json:"vehicle_id"`
	StopID         uuid.UUID        `json:"stop_id"`
	AcademicYearID uuid.UUID        `json:"academic_year_id"`
	AllocationDate pgtype.Date      `json:"allocation_date"`
	IsActive       pgtype.Bool      `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type Subject struct {
	SubjectID   uuid.UUID        `json:"subject_id"`
	SubjectName string           `json:"subject_name"`
	SubjectCode string           `json:"subject_code"`
	Description pgtype.Text      `json:"description"`
	IsMandatory pgtype.Bool      `json:"is_mandatory"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type SubjectSyllabus struct {
	SyllabusID       uuid.UUID        `json:"syllabus_id"`
	SubjectID        uuid.UUID        `json:"subject_id"`
	AcademicYearID   uuid.UUID        `json:"academic_year_id"`
	Curriculum       pgtype.Text      `json:"curriculum"`
	LearningOutcomes pgtype.Text      `json:"learning_outcomes"`
	TeachingMethod   pgtype.Text      `json:"teaching_method"`
	AssessmentMethod pgtype.Text      `json:"assessment_method"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
}

type SystemSetting struct {
	SettingID    uuid.UUID        `json:"setting_id"`
	SettingKey   string           `json:"setting_key"`
	SettingValue pgtype.Text      `json:"setting_value"`
	SettingType  pgtype.Text      `json:"setting_type"`
	Description  pgtype.Text      `json:"description"`
	IsEditable   pgtype.Bool      `json:"is_editable"`
	OrgID        pgtype.UUID      `json:"org_id"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type Timetable struct {
	TimetableID    uuid.UUID        `json:"timetable_id"`
	SectionID      uuid.UUID        `json:"section_id"`
	AcademicYearID uuid.UUID        `json:"academic_year_id"`
	ClassLevelID   uuid.UUID        `json:"class_level_id"`
	TimetableName  pgtype.Text      `json:"timetable_name"`
	IsActive       pgtype.Bool      `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type TimetableEntry struct {
	EntryID      uuid.UUID        `json:"entry_id"`
	TimetableID  uuid.UUID        `json:"timetable_id"`
	DayOfWeek    pgtype.Int4      `json:"day_of_week"`
	PeriodNumber pgtype.Int4      `json:"period_number"`
	StartTime    pgtype.Time      `json:"start_time"`
	EndTime      pgtype.Time      `json:"end_time"`
	SubjectID    uuid.UUID        `json:"subject_id"`
	StaffID      pgtype.UUID      `json:"staff_id"`
	RoomNumber   pgtype.Text      `json:"room_number"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type TransportFee struct {
	TransportFeeID uuid.UUID        `json:"transport_fee_id"`
	RouteID        uuid.UUID        `json:"route_id"`
	AcademicYearID uuid.UUID        `json:"academic_year_id"`
	FeeAmount      pgtype.Numeric   `json:"fee_amount"`
	IsActive       pgtype.Bool      `json:"is_active"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type TransportRoute struct {
	RouteID           uuid.UUID        `json:"route_id"`
	OrgID             uuid.UUID        `json:"org_id"`
	RouteName         string           `json:"route_name"`
	RouteCode         string           `json:"route_code"`
	StartLocation     pgtype.Text      `json:"start_location"`
	EndLocation       pgtype.Text      `json:"end_location"`
	TotalStops        pgtype.Int4      `json:"total_stops"`
	EstimatedDuration pgtype.Int4      `json:"estimated_duration"`
	RouteMap          []byte           `json:"route_map"`
	IsActive          pgtype.Bool      `json:"is_active"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type TransportStop struct {
	StopID       uuid.UUID        `json:"stop_id"`
	RouteID      uuid.UUID        `json:"route_id"`
	StopName     pgtype.Text      `json:"stop_name"`
	StopSequence pgtype.Int4      `json:"stop_sequence"`
	Latitude     pgtype.Numeric   `json:"latitude"`
	Longitude    pgtype.Numeric   `json:"longitude"`
	StopTime     pgtype.Time      `json:"stop_time"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type User struct {
	UserID            uuid.UUID        `json:"user_id"`
	OrgID             uuid.UUID        `json:"org_id"`
	Username          string           `json:"username"`
	Email             string           `json:"email"`
	PasswordHash      string           `json:"password_hash"`
	FirstName         string           `json:"first_name"`
	LastName          string           `json:"last_name"`
	PhoneNumber       pgtype.Text      `json:"phone_number"`
	DateOfBirth       pgtype.Date      `json:"date_of_birth"`
	Gender            pgtype.Text      `json:"gender"`
	Address           pgtype.Text      `json:"address"`
	City              pgtype.Text      `json:"city"`
	State             pgtype.Text      `json:"state"`
	Country           pgtype.Text      `json:"country"`
	PostalCode        pgtype.Text      `json:"postal_code"`
	ProfilePictureUrl pgtype.Text      `json:"profile_picture_url"`
	Status            pgtype.Text      `json:"status"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	LastLogin         pgtype.Timestamp `json:"last_login"`
}

type UserRole struct {
	UserID     uuid.UUID        `json:"user_id"`
	RoleID     int32            `json:"role_id"`
	OrgID      uuid.UUID        `json:"org_id"`
	AssignedAt pgtype.Timestamp `json:"assigned_at"`
}

type Vehicle struct {
	VehicleID                  uuid.UUID        `json:"vehicle_id"`
	OrgID                      uuid.UUID        `json:"org_id"`
	VehicleNumber              string           `json:"vehicle_number"`
	VehicleType                pgtype.Text      `json:"vehicle_type"`
	VehicleModel               pgtype.Text      `json:"vehicle_model"`
	RegistrationNumber         pgtype.Text      `json:"registration_number"`
	VehicleCapacity            pgtype.Int4      `json:"vehicle_capacity"`
	PurchaseDate               pgtype.Date      `json:"purchase_date"`
	LastMaintenanceDate        pgtype.Date      `json:"last_maintenance_date"`
	NextMaintenanceDate        pgtype.Date      `json:"next_maintenance_date"`
	InsuranceExpiry            pgtype.Date      `json:"insurance_expiry"`
	PollutionCertificateExpiry pgtype.Date      `json:"pollution_certificate_expiry"`
	VehicleStatus              pgtype.Text      `json:"vehicle_status"`
	GpsDeviceID                pgtype.Text      `json:"gps_device_id"`
	CreatedAt                  pgtype.Timestamp `json:"created_at"`
}

type VehicleDriver struct {
	AssignmentID uuid.UUID   `json:"assignment_id"`
	VehicleID    uuid.UUID   `json:"vehicle_id"`
	DriverID     uuid.UUID   `json:"driver_id"`
	AssignedDate pgtype.Date `json:"assigned_date"`
	IsActive     pgtype.Bool `json:"is_active"`
}

type VehicleGpsTracking struct {
	TrackingID        uuid.UUID        `json:"tracking_id"`
	VehicleID         uuid.UUID        `json:"vehicle_id"`
	Latitude          pgtype.Numeric   `json:"latitude"`
	Longitude         pgtype.Numeric   `json:"longitude"`
	Speed             pgtype.Numeric   `json:"speed"`
	Heading           pgtype.Int4      `json:"heading"`
	TrackingTimestamp pgtype.Timestamp `json:"tracking_timestamp"`
}

type VisitorManagement struct {
	VisitorID      uuid.UUID        `json:"visitor_id"`
	OrgID          uuid.UUID        `json:"org_id"`
	VisitorName    pgtype.Text      `json:"visitor_name"`
	VisitorPhone   pgtype.Text      `json:"visitor_phone"`
	VisitorEmail   pgtype.Text      `json:"visitor_email"`
	PurposeOfVisit pgtype.Text      `json:"purpose_of_visit"`
	VisitDate      pgtype.Date      `json:"visit_date"`
	CheckInTime    pgtype.Time      `json:"check_in_time"`
	CheckOutTime   pgtype.Time      `json:"check_out_time"`
	HostID         pgtype.UUID      `json:"host_id"`
	IDProofType    pgtype.Text      `json:"id_proof_type"`
	IDProofNumber  pgtype.Text      `json:"id_proof_number"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}
