// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: onboard.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const callSeedTenantRoles = `-- name: CallSeedTenantRoles :exec
SELECT seed_tenant_roles($1)
`

func (q *Queries) CallSeedTenantRoles(ctx context.Context, pTenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, callSeedTenantRoles, pTenantID)
	return err
}

const countSubscriptionPlans = `-- name: CountSubscriptionPlans :one
SELECT COUNT(*) FROM subscription_plans
`

func (q *Queries) CountSubscriptionPlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscriptionPlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTenantRoles = `-- name: CountTenantRoles :one

SELECT COUNT(*) FROM roles WHERE tenant_id = $1
`

// ============================================================================
// ROLES & PERMISSIONS (automatic seeding)
// ============================================================================
func (q *Queries) CountTenantRoles(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantRoles, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :one

INSERT INTO tenants (
    id, name, subdomain, slug, timezone, country, state, city, address, pincode,
    contact_email, contact_phone, website, status, subscription_plan_id,
    subscription_start_date, subscription_end_date, trial_ends_at, api_key, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
) RETURNING id
`

type CreateTenantParams struct {
	ID                    uuid.UUID          `json:"id"`
	Name                  string             `json:"name"`
	Subdomain             string             `json:"subdomain"`
	Slug                  string             `json:"slug"`
	Timezone              string             `json:"timezone"`
	Country               *string            `json:"country"`
	State                 *string            `json:"state"`
	City                  *string            `json:"city"`
	Address               *string            `json:"address"`
	Pincode               *string            `json:"pincode"`
	ContactEmail          *string            `json:"contact_email"`
	ContactPhone          *string            `json:"contact_phone"`
	Website               *string            `json:"website"`
	Status                TenantStatus       `json:"status"`
	SubscriptionPlanID    pgtype.UUID        `json:"subscription_plan_id"`
	SubscriptionStartDate pgtype.Date        `json:"subscription_start_date"`
	SubscriptionEndDate   pgtype.Date        `json:"subscription_end_date"`
	TrialEndsAt           pgtype.Timestamptz `json:"trial_ends_at"`
	ApiKey                *string            `json:"api_key"`
	Metadata              []byte             `json:"metadata"`
}

// ============================================================================
// TENANT & SUBSCRIPTION
// ============================================================================
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.Subdomain,
		arg.Slug,
		arg.Timezone,
		arg.Country,
		arg.State,
		arg.City,
		arg.Address,
		arg.Pincode,
		arg.ContactEmail,
		arg.ContactPhone,
		arg.Website,
		arg.Status,
		arg.SubscriptionPlanID,
		arg.SubscriptionStartDate,
		arg.SubscriptionEndDate,
		arg.TrialEndsAt,
		arg.ApiKey,
		arg.Metadata,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAcademicYearByName = `-- name: GetAcademicYearByName :one

SELECT id FROM academic_years
WHERE tenant_id = $1 AND name = $2
LIMIT 1
`

type GetAcademicYearByNameParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

// ============================================================================
// ACADEMIC YEARS
// Unique: (tenant_id, name)
// ============================================================================
func (q *Queries) GetAcademicYearByName(ctx context.Context, arg GetAcademicYearByNameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getAcademicYearByName, arg.TenantID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getClassByGradeAndYear = `-- name: GetClassByGradeAndYear :one
SELECT c.id
FROM classes c
JOIN grades g ON g.id = c.grade_id
JOIN academic_years ay ON ay.id = c.academic_year_id
WHERE c.tenant_id = $1 AND g.name = $2 AND ay.name = $3
LIMIT 1
`

type GetClassByGradeAndYearParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Name_2   string    `json:"name_2"`
}

func (q *Queries) GetClassByGradeAndYear(ctx context.Context, arg GetClassByGradeAndYearParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getClassByGradeAndYear, arg.TenantID, arg.Name, arg.Name_2)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getClassByName = `-- name: GetClassByName :one

SELECT id FROM classes
WHERE tenant_id = $1 AND name = $2
LIMIT 1
`

type GetClassByNameParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

// ============================================================================
// CLASSES
// Unique: (tenant_id, name) – we assume class names are unique per tenant.
// ============================================================================
func (q *Queries) GetClassByName(ctx context.Context, arg GetClassByNameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getClassByName, arg.TenantID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getClassSubjectByClassAndSubject = `-- name: GetClassSubjectByClassAndSubject :one

SELECT cs.id
FROM class_subjects cs
JOIN classes c ON c.id = cs.class_id
JOIN subjects s ON s.id = cs.subject_id
WHERE c.tenant_id = $1 AND c.name = $2 AND s.code = $3
LIMIT 1
`

type GetClassSubjectByClassAndSubjectParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Code     string    `json:"code"`
}

// ============================================================================
// CLASS SUBJECTS
// Unique: (class_id, subject_id)
// ============================================================================
func (q *Queries) GetClassSubjectByClassAndSubject(ctx context.Context, arg GetClassSubjectByClassAndSubjectParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getClassSubjectByClassAndSubject, arg.TenantID, arg.Name, arg.Code)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getDepartmentByName = `-- name: GetDepartmentByName :one

SELECT id FROM departments
WHERE tenant_id = $1 AND name = $2
LIMIT 1
`

type GetDepartmentByNameParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

// ============================================================================
// DEPARTMENTS
// Unique: (tenant_id, name)
// ============================================================================
func (q *Queries) GetDepartmentByName(ctx context.Context, arg GetDepartmentByNameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDepartmentByName, arg.TenantID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getFeeStructureByNaturalKey = `-- name: GetFeeStructureByNaturalKey :one

SELECT fs.id
FROM fee_structures fs
JOIN academic_years ay ON ay.id = fs.academic_year_id
JOIN classes c ON c.id = fs.class_id
WHERE fs.tenant_id = $1
  AND ay.name = $2
  AND c.name = $3
  AND fs.fee_type = $4
  AND fs.name = $5
LIMIT 1
`

type GetFeeStructureByNaturalKeyParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Name_2   string    `json:"name_2"`
	FeeType  FeeType   `json:"fee_type"`
	Name_3   string    `json:"name_3"`
}

// ============================================================================
// FEE STRUCTURES
// Unique: (tenant_id, academic_year_id, class_id, fee_type, name)
// ============================================================================
func (q *Queries) GetFeeStructureByNaturalKey(ctx context.Context, arg GetFeeStructureByNaturalKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getFeeStructureByNaturalKey,
		arg.TenantID,
		arg.Name,
		arg.Name_2,
		arg.FeeType,
		arg.Name_3,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getGradeByName = `-- name: GetGradeByName :one

SELECT id FROM grades
WHERE tenant_id = $1 AND name = $2
LIMIT 1
`

type GetGradeByNameParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
}

// ============================================================================
// GRADES
// Unique: (tenant_id, name)
// ============================================================================
func (q *Queries) GetGradeByName(ctx context.Context, arg GetGradeByNameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getGradeByName, arg.TenantID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSectionByClassAndName = `-- name: GetSectionByClassAndName :one

SELECT s.id
FROM sections s
JOIN classes c ON c.id = s.class_id
WHERE c.tenant_id = $1 AND c.name = $2 AND s.name = $3
LIMIT 1
`

type GetSectionByClassAndNameParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Name     string    `json:"name"`
	Name_2   string    `json:"name_2"`
}

// ============================================================================
// SECTIONS
// Unique: (class_id, name). For upsert we need class_id.
// ============================================================================
func (q *Queries) GetSectionByClassAndName(ctx context.Context, arg GetSectionByClassAndNameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSectionByClassAndName, arg.TenantID, arg.Name, arg.Name_2)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSubjectByCode = `-- name: GetSubjectByCode :one

SELECT id FROM subjects
WHERE tenant_id = $1 AND code = $2
LIMIT 1
`

type GetSubjectByCodeParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Code     string    `json:"code"`
}

// ============================================================================
// SUBJECTS
// Unique: (tenant_id, code)
// ============================================================================
func (q *Queries) GetSubjectByCode(ctx context.Context, arg GetSubjectByCodeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSubjectByCode, arg.TenantID, arg.Code)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSubscriptionPlanIDByName = `-- name: GetSubscriptionPlanIDByName :one
SELECT id FROM subscription_plans
WHERE name = $1 AND billing_period = $2
LIMIT 1
`

type GetSubscriptionPlanIDByNameParams struct {
	Name          string        `json:"name"`
	BillingPeriod BillingPeriod `json:"billing_period"`
}

func (q *Queries) GetSubscriptionPlanIDByName(ctx context.Context, arg GetSubscriptionPlanIDByNameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSubscriptionPlanIDByName, arg.Name, arg.BillingPeriod)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getTenantSetting = `-- name: GetTenantSetting :one

SELECT id FROM tenant_settings WHERE tenant_id = $1 LIMIT 1
`

// ============================================================================
// TENANT SETTINGS
// Unique: tenant_id
// ============================================================================
func (q *Queries) GetTenantSetting(ctx context.Context, tenantID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTenantSetting, tenantID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id FROM users
WHERE tenant_id = $1 AND email = $2
LIMIT 1
`

type GetUserByEmailParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    *string     `json:"email"`
}

// ============================================================================
// USERS (teacher placeholders)
// Unique: (tenant_id, email)
// ============================================================================
func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.TenantID, arg.Email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertAcademicYear = `-- name: UpsertAcademicYear :one
INSERT INTO academic_years (id, tenant_id, name, start_date, end_date, is_current)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, name) DO UPDATE SET
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    is_current = EXCLUDED.is_current
RETURNING id
`

type UpsertAcademicYearParams struct {
	ID        uuid.UUID   `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	Name      string      `json:"name"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	IsCurrent bool        `json:"is_current"`
}

func (q *Queries) UpsertAcademicYear(ctx context.Context, arg UpsertAcademicYearParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertAcademicYear,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.IsCurrent,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertClass = `-- name: UpsertClass :one
INSERT INTO classes (
    id, tenant_id, grade_id, academic_year_id, name, max_students, room_number
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (tenant_id, name) DO UPDATE SET
    grade_id = EXCLUDED.grade_id,
    academic_year_id = EXCLUDED.academic_year_id,
    max_students = EXCLUDED.max_students,
    room_number = EXCLUDED.room_number
RETURNING id
`

type UpsertClassParams struct {
	ID             uuid.UUID `json:"id"`
	TenantID       uuid.UUID `json:"tenant_id"`
	GradeID        uuid.UUID `json:"grade_id"`
	AcademicYearID uuid.UUID `json:"academic_year_id"`
	Name           string    `json:"name"`
	MaxStudents    *int32    `json:"max_students"`
	RoomNumber     *string   `json:"room_number"`
}

func (q *Queries) UpsertClass(ctx context.Context, arg UpsertClassParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertClass,
		arg.ID,
		arg.TenantID,
		arg.GradeID,
		arg.AcademicYearID,
		arg.Name,
		arg.MaxStudents,
		arg.RoomNumber,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertClassSubject = `-- name: UpsertClassSubject :one
INSERT INTO class_subjects (id, class_id, subject_id, teacher_id, periods_per_week)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (class_id, subject_id) DO UPDATE SET
    teacher_id = EXCLUDED.teacher_id,
    periods_per_week = EXCLUDED.periods_per_week
RETURNING id
`

type UpsertClassSubjectParams struct {
	ID             uuid.UUID   `json:"id"`
	ClassID        uuid.UUID   `json:"class_id"`
	SubjectID      uuid.UUID   `json:"subject_id"`
	TeacherID      pgtype.UUID `json:"teacher_id"`
	PeriodsPerWeek *int16      `json:"periods_per_week"`
}

func (q *Queries) UpsertClassSubject(ctx context.Context, arg UpsertClassSubjectParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertClassSubject,
		arg.ID,
		arg.ClassID,
		arg.SubjectID,
		arg.TeacherID,
		arg.PeriodsPerWeek,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertDepartment = `-- name: UpsertDepartment :one
INSERT INTO departments (id, tenant_id, name, description, head_teacher_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, name) DO UPDATE SET
    description = EXCLUDED.description,
    head_teacher_id = EXCLUDED.head_teacher_id
RETURNING id
`

type UpsertDepartmentParams struct {
	ID            uuid.UUID   `json:"id"`
	TenantID      uuid.UUID   `json:"tenant_id"`
	Name          string      `json:"name"`
	Description   *string     `json:"description"`
	HeadTeacherID pgtype.UUID `json:"head_teacher_id"`
}

func (q *Queries) UpsertDepartment(ctx context.Context, arg UpsertDepartmentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertDepartment,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.HeadTeacherID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertFeeStructure = `-- name: UpsertFeeStructure :one
INSERT INTO fee_structures (
    id, tenant_id, academic_year_id, class_id, fee_type, name,
    amount, frequency, due_day, due_date, late_fee_per_day, is_mandatory, description
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (tenant_id, academic_year_id, class_id, fee_type, name) DO UPDATE SET
    amount = EXCLUDED.amount,
    frequency = EXCLUDED.frequency,
    due_day = EXCLUDED.due_day,
    due_date = EXCLUDED.due_date,
    late_fee_per_day = EXCLUDED.late_fee_per_day,
    is_mandatory = EXCLUDED.is_mandatory,
    description = EXCLUDED.description
RETURNING id
`

type UpsertFeeStructureParams struct {
	ID             uuid.UUID      `json:"id"`
	TenantID       uuid.UUID      `json:"tenant_id"`
	AcademicYearID uuid.UUID      `json:"academic_year_id"`
	ClassID        pgtype.UUID    `json:"class_id"`
	FeeType        FeeType        `json:"fee_type"`
	Name           string         `json:"name"`
	Amount         pgtype.Numeric `json:"amount"`
	Frequency      FeeFrequency   `json:"frequency"`
	DueDay         *int16         `json:"due_day"`
	DueDate        pgtype.Date    `json:"due_date"`
	LateFeePerDay  pgtype.Numeric `json:"late_fee_per_day"`
	IsMandatory    bool           `json:"is_mandatory"`
	Description    *string        `json:"description"`
}

func (q *Queries) UpsertFeeStructure(ctx context.Context, arg UpsertFeeStructureParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertFeeStructure,
		arg.ID,
		arg.TenantID,
		arg.AcademicYearID,
		arg.ClassID,
		arg.FeeType,
		arg.Name,
		arg.Amount,
		arg.Frequency,
		arg.DueDay,
		arg.DueDate,
		arg.LateFeePerDay,
		arg.IsMandatory,
		arg.Description,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertGrade = `-- name: UpsertGrade :one
INSERT INTO grades (id, tenant_id, name, sequence, description)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, name) DO UPDATE SET
    sequence = EXCLUDED.sequence,
    description = EXCLUDED.description
RETURNING id
`

type UpsertGradeParams struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	Sequence    int16     `json:"sequence"`
	Description *string   `json:"description"`
}

func (q *Queries) UpsertGrade(ctx context.Context, arg UpsertGradeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertGrade,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Sequence,
		arg.Description,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertPlaceholderUser = `-- name: UpsertPlaceholderUser :one
INSERT INTO users (
    id, tenant_id, username, email, password_hash, first_name, last_name,
    status, created_offline_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'active', NOW()
)
ON CONFLICT (tenant_id, email) DO UPDATE SET
    username = EXCLUDED.username,
    password_hash = EXCLUDED.password_hash,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    status = EXCLUDED.status
RETURNING id
`

type UpsertPlaceholderUserParams struct {
	ID           uuid.UUID   `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	Username     string      `json:"username"`
	Email        *string     `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FirstName    string      `json:"first_name"`
	LastName     *string     `json:"last_name"`
}

func (q *Queries) UpsertPlaceholderUser(ctx context.Context, arg UpsertPlaceholderUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPlaceholderUser,
		arg.ID,
		arg.TenantID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertSection = `-- name: UpsertSection :one
INSERT INTO sections (id, class_id, name, teacher_id, max_students)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (class_id, name) DO UPDATE SET
    teacher_id = EXCLUDED.teacher_id,
    max_students = EXCLUDED.max_students
RETURNING id
`

type UpsertSectionParams struct {
	ID          uuid.UUID   `json:"id"`
	ClassID     uuid.UUID   `json:"class_id"`
	Name        string      `json:"name"`
	TeacherID   pgtype.UUID `json:"teacher_id"`
	MaxStudents *int32      `json:"max_students"`
}

func (q *Queries) UpsertSection(ctx context.Context, arg UpsertSectionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertSection,
		arg.ID,
		arg.ClassID,
		arg.Name,
		arg.TeacherID,
		arg.MaxStudents,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertSubject = `-- name: UpsertSubject :one
INSERT INTO subjects (
    id, tenant_id, name, code, department_id, grade_id, is_elective, credits
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (tenant_id, code) DO UPDATE SET
    name = EXCLUDED.name,
    department_id = EXCLUDED.department_id,
    grade_id = EXCLUDED.grade_id,
    is_elective = EXCLUDED.is_elective,
    credits = EXCLUDED.credits
RETURNING id
`

type UpsertSubjectParams struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	Name         string         `json:"name"`
	Code         string         `json:"code"`
	DepartmentID pgtype.UUID    `json:"department_id"`
	GradeID      pgtype.UUID    `json:"grade_id"`
	IsElective   bool           `json:"is_elective"`
	Credits      pgtype.Numeric `json:"credits"`
}

func (q *Queries) UpsertSubject(ctx context.Context, arg UpsertSubjectParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertSubject,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Code,
		arg.DepartmentID,
		arg.GradeID,
		arg.IsElective,
		arg.Credits,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertTenantSetting = `-- name: UpsertTenantSetting :one
INSERT INTO tenant_settings (
    id, tenant_id, session_timeout_min, max_users, max_students,
    academic_year_format, date_format, currency_code, grading_system,
    attendance_mode, sms_gateway, email_provider, features_enabled, theme
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
ON CONFLICT (tenant_id) DO UPDATE SET
    session_timeout_min = EXCLUDED.session_timeout_min,
    max_users = EXCLUDED.max_users,
    max_students = EXCLUDED.max_students,
    academic_year_format = EXCLUDED.academic_year_format,
    date_format = EXCLUDED.date_format,
    currency_code = EXCLUDED.currency_code,
    grading_system = EXCLUDED.grading_system,
    attendance_mode = EXCLUDED.attendance_mode,
    sms_gateway = EXCLUDED.sms_gateway,
    email_provider = EXCLUDED.email_provider,
    features_enabled = EXCLUDED.features_enabled,
    theme = EXCLUDED.theme
RETURNING id
`

type UpsertTenantSettingParams struct {
	ID                 uuid.UUID `json:"id"`
	TenantID           uuid.UUID `json:"tenant_id"`
	SessionTimeoutMin  int32     `json:"session_timeout_min"`
	MaxUsers           *int32    `json:"max_users"`
	MaxStudents        *int32    `json:"max_students"`
	AcademicYearFormat *string   `json:"academic_year_format"`
	DateFormat         *string   `json:"date_format"`
	CurrencyCode       *string   `json:"currency_code"`
	GradingSystem      *string   `json:"grading_system"`
	AttendanceMode     *string   `json:"attendance_mode"`
	SmsGateway         *string   `json:"sms_gateway"`
	EmailProvider      *string   `json:"email_provider"`
	FeaturesEnabled    []byte    `json:"features_enabled"`
	Theme              []byte    `json:"theme"`
}

func (q *Queries) UpsertTenantSetting(ctx context.Context, arg UpsertTenantSettingParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertTenantSetting,
		arg.ID,
		arg.TenantID,
		arg.SessionTimeoutMin,
		arg.MaxUsers,
		arg.MaxStudents,
		arg.AcademicYearFormat,
		arg.DateFormat,
		arg.CurrencyCode,
		arg.GradingSystem,
		arg.AttendanceMode,
		arg.SmsGateway,
		arg.EmailProvider,
		arg.FeaturesEnabled,
		arg.Theme,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
