// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shashisharma307703/vedantam/db/types"
)

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations 
WHERE org_id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, orgID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganization, orgID)
	return err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT org_id, org_name, org_code, phone_number, email, website, 
       logo_url, address, city, state, country, postal_code, 
       established_date, affiliation_number, license_number, license_expiry, 
       created_at, updated_at
FROM organizations 
WHERE org_id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, orgID uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, orgID)
	var i Organization
	err := row.Scan(
		&i.OrgID,
		&i.OrgName,
		&i.OrgCode,
		&i.PhoneNumber,
		&i.Email,
		&i.Website,
		&i.LogoUrl,
		&i.Address,
		&i.City,
		&i.State,
		&i.Country,
		&i.PostalCode,
		&i.EstablishedDate,
		&i.AffiliationNumber,
		&i.LicenseNumber,
		&i.LicenseExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const replaceOrganization = `-- name: ReplaceOrganization :one
UPDATE organizations
SET org_name = $2, 
    org_code = $3, 
    phone_number = $4, 
    email = $5, 
    website = $6,
    logo_url = $7, 
    address = $8, 
    city = $9, 
    state = $10, 
    country = $11, 
    postal_code = $12,
    established_date = $13, 
    affiliation_number = $14, 
    license_number = $15, 
    license_expiry = $16,
    updated_at = CURRENT_TIMESTAMP
WHERE org_id = $1
RETURNING org_id, org_name, org_code, phone_number, email, website, logo_url, address, city, state, country, postal_code, established_date, affiliation_number, license_number, license_expiry, created_at, updated_at
`

type ReplaceOrganizationParams struct {
	OrgID             uuid.UUID        `json:"org_id"`
	OrgName           string           `json:"org_name"`
	OrgCode           string           `json:"org_code"`
	PhoneNumber       pgtype.Text      `json:"phone_number"`
	Email             pgtype.Text      `json:"email"`
	Website           pgtype.Text      `json:"website"`
	LogoUrl           pgtype.Text      `json:"logo_url"`
	Address           pgtype.Text      `json:"address"`
	City              pgtype.Text      `json:"city"`
	State             pgtype.Text      `json:"state"`
	Country           pgtype.Text      `json:"country"`
	PostalCode        pgtype.Text      `json:"postal_code"`
	EstablishedDate   types.CustomDate `json:"established_date"`
	AffiliationNumber pgtype.Text      `json:"affiliation_number"`
	LicenseNumber     pgtype.Text      `json:"license_number"`
	LicenseExpiry     types.CustomDate `json:"license_expiry"`
}

func (q *Queries) ReplaceOrganization(ctx context.Context, arg ReplaceOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, replaceOrganization,
		arg.OrgID,
		arg.OrgName,
		arg.OrgCode,
		arg.PhoneNumber,
		arg.Email,
		arg.Website,
		arg.LogoUrl,
		arg.Address,
		arg.City,
		arg.State,
		arg.Country,
		arg.PostalCode,
		arg.EstablishedDate,
		arg.AffiliationNumber,
		arg.LicenseNumber,
		arg.LicenseExpiry,
	)
	var i Organization
	err := row.Scan(
		&i.OrgID,
		&i.OrgName,
		&i.OrgCode,
		&i.PhoneNumber,
		&i.Email,
		&i.Website,
		&i.LogoUrl,
		&i.Address,
		&i.City,
		&i.State,
		&i.Country,
		&i.PostalCode,
		&i.EstablishedDate,
		&i.AffiliationNumber,
		&i.LicenseNumber,
		&i.LicenseExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrganization = `-- name: UpsertOrganization :one
INSERT INTO organizations (
    org_id, org_name, org_code, phone_number, email, website, 
    logo_url, address, city, state, country, postal_code, 
    established_date, affiliation_number, license_number, license_expiry
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (org_id) 
DO UPDATE SET 
    org_name = EXCLUDED.org_name,
    org_code = EXCLUDED.org_code,
    phone_number = EXCLUDED.phone_number,
    email = EXCLUDED.email,
    website = EXCLUDED.website,
    logo_url = EXCLUDED.logo_url,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    country = EXCLUDED.country,
    postal_code = EXCLUDED.postal_code,
    established_date = EXCLUDED.established_date,
    affiliation_number = EXCLUDED.affiliation_number,
    license_number = EXCLUDED.license_number,
    license_expiry = EXCLUDED.license_expiry,
    updated_at = CURRENT_TIMESTAMP
RETURNING org_id, org_name, org_code, phone_number, email, website, logo_url, address, city, state, country, postal_code, established_date, affiliation_number, license_number, license_expiry, created_at, updated_at
`

type UpsertOrganizationParams struct {
	OrgID             uuid.UUID        `json:"org_id"`
	OrgName           string           `json:"org_name"`
	OrgCode           string           `json:"org_code"`
	PhoneNumber       pgtype.Text      `json:"phone_number"`
	Email             pgtype.Text      `json:"email"`
	Website           pgtype.Text      `json:"website"`
	LogoUrl           pgtype.Text      `json:"logo_url"`
	Address           pgtype.Text      `json:"address"`
	City              pgtype.Text      `json:"city"`
	State             pgtype.Text      `json:"state"`
	Country           pgtype.Text      `json:"country"`
	PostalCode        pgtype.Text      `json:"postal_code"`
	EstablishedDate   types.CustomDate `json:"established_date"`
	AffiliationNumber pgtype.Text      `json:"affiliation_number"`
	LicenseNumber     pgtype.Text      `json:"license_number"`
	LicenseExpiry     types.CustomDate `json:"license_expiry"`
}

func (q *Queries) UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, upsertOrganization,
		arg.OrgID,
		arg.OrgName,
		arg.OrgCode,
		arg.PhoneNumber,
		arg.Email,
		arg.Website,
		arg.LogoUrl,
		arg.Address,
		arg.City,
		arg.State,
		arg.Country,
		arg.PostalCode,
		arg.EstablishedDate,
		arg.AffiliationNumber,
		arg.LicenseNumber,
		arg.LicenseExpiry,
	)
	var i Organization
	err := row.Scan(
		&i.OrgID,
		&i.OrgName,
		&i.OrgCode,
		&i.PhoneNumber,
		&i.Email,
		&i.Website,
		&i.LogoUrl,
		&i.Address,
		&i.City,
		&i.State,
		&i.Country,
		&i.PostalCode,
		&i.EstablishedDate,
		&i.AffiliationNumber,
		&i.LicenseNumber,
		&i.LicenseExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
