// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteClass(ctx context.Context, classLevelID uuid.UUID) error
	DeleteOrganization(ctx context.Context, orgID uuid.UUID) error
	GetClassByID(ctx context.Context, classLevelID uuid.UUID) (ClassLevel, error)
	GetOrganizationByID(ctx context.Context, orgID uuid.UUID) (Organization, error)
	ReplaceClass(ctx context.Context, arg ReplaceClassParams) (ClassLevel, error)
	ReplaceOrganization(ctx context.Context, arg ReplaceOrganizationParams) (Organization, error)
	UpsertClass(ctx context.Context, arg UpsertClassParams) (ClassLevel, error)
	UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) (Organization, error)
}

var _ Querier = (*Queries)(nil)
